import { Inter } from 'next/font/google';
import './globals.css';
import Submenu from '@/components/Trial/Submenu';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" w-full max-w-[1400px] mx-auto">
          <Submenu />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
